# Generated by Django 5.2.12 on 2026-03-19 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='backend.user'),
        ),
        migrations.AlterUniqueTogether(
            name='api',
            unique_together={('user', 'model_name')},
        ),
    ]
