# Generated by Django 5.2.12 on 2026-03-21 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_user_google_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='user_interests',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='user_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='setting',
            name='user_role',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
