# Generated by Django 5.2.12 on 2026-03-21 10:42

import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_setting_user_interests_setting_user_name_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='history_id',
            new_name='chat_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='timestamp',
            new_name='created_at',
        ),
        migrations.AddField(
            model_name='chat',
            name='session_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4),
        ),
        migrations.AddField(
            model_name='setting',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chat',
            name='task_type',
            field=models.CharField(default='text', max_length=50),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user_instruction',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'session_id'], name='chat_user_id_acfc55_idx'),
        ),
        migrations.AddIndex(
            model_name='chat',
            index=models.Index(fields=['user', 'created_at'], name='chat_user_id_995d74_idx'),
        ),
        migrations.AlterModelTable(
            name='api',
            table='api',
        ),
        migrations.AlterModelTable(
            name='chat',
            table='chat',
        ),
        migrations.AlterModelTable(
            name='setting',
            table='setting',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
