# Generated by Django 5.2.12 on 2026-03-21 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0005_alter_chat_options_rename_history_id_chat_chat_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='setting',
            name='created_at',
        ),
    ]
