# Generated by Django 5.2.12 on 2026-03-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0006_remove_setting_created_at'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chat',
            options={},
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_user_id_acfc55_idx',
        ),
        migrations.RemoveIndex(
            model_name='chat',
            name='chat_user_id_995d74_idx',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='chat_id',
            new_name='history_id',
        ),
        migrations.RenameField(
            model_name='chat',
            old_name='created_at',
            new_name='timestamp',
        ),
        migrations.RemoveField(
            model_name='chat',
            name='session_id',
        ),
        migrations.AlterField(
            model_name='chat',
            name='task_type',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user_instruction',
            field=models.JSONField(blank=True, null=True),
        ),
        migrations.AlterModelTable(
            name='api',
            table=None,
        ),
        migrations.AlterModelTable(
            name='chat',
            table=None,
        ),
        migrations.AlterModelTable(
            name='setting',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user',
            table=None,
        ),
    ]
