# Generated by Django 5.2.12 on 2026-03-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0008_chatsession_chat_session'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='enable_custom_instructions',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='setting',
            name='user_instruction',
            field=models.TextField(blank=True, null=True),
        ),
    ]
