# Generated by Django 5.2.12 on 2026-04-10 06:35

import backend.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0009_setting_enable_custom_instructions_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='chat',
            name='input_text',
            field=backend.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='chat',
            name='output_text',
            field=backend.models.EncryptedTextField(),
        ),
    ]
