# Generated by Django 5.2.7 on 2026-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0011_sessionfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='setting',
            name='auto_read_aloud',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='setting',
            name='remember_history',
            field=models.BooleanField(default=False),
        ),
        migrations.DeleteModel(
            name='SessionFile',
        ),
    ]
