# Generated by Django 5.2.7 on 2026-07-21 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0012_setting_auto_read_aloud_setting_remember_history_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnonymousUsage',
            fields=[
                ('user_key', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('message_count', models.IntegerField(default=0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
