"""
Django settings for hero_ai project.

Generated by 'django-admin startproject' using Django 5.2.7.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""


from pathlib import Path
import os
from dotenv import load_dotenv
from cryptography.fernet import Fernet


load_dotenv() 

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Encryption key for API keys
ENCRYPTION_KEY = os.getenv('ENCRYPTION_KEY', '').encode()

# Session configuration
SESSION_ENGINE = 'django.contrib.sessions.backends.db'
SESSION_COOKIE_AGE = 1209600  # 2 weeks
SESSION_COOKIE_HTTPONLY = True
SESSION_COOKIE_SECURE = False  # Set to True in production with HTTPS
SESSION_SAVE_EVERY_REQUEST = False

# CSRF settings
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SECURE = False  # Set to True in production with HTTPS
CSRF_USE_SESSIONS = False

# Authentication
AUTH_USER_MODEL = 'auth.User'  # Use default Django user model

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY', 'django-insecure-fallback-key-change-in-production')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.getenv('DEBUG', 'False') == 'True'

ALLOWED_HOSTS = os.getenv('ALLOWED_HOSTS', '127.0.0.1,localhost').split(',')


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'backend'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',  # Serve static files in production
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'hero_ai.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'hero_ai.wsgi.application'

# Use environment variables for Google OAuth
GOOGLE_CLIENT_ID = os.getenv('GOOGLE_CLIENT_ID', '')
GOOGLE_CLIENT_SECRET = os.getenv('GOOGLE_CLIENT_SECRET', '')
SITE_URL = os.getenv('SITE_URL', 'http://localhost:8000')

# Better CSRF settings
CSRF_COOKIE_HTTPONLY = True  
CSRF_TRUSTED_ORIGINS = [SITE_URL]  

# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': os.getenv('NEON_DB_NAME'),
        'USER': os.getenv('NEON_DB_USER'),
        'PASSWORD': os.getenv('NEON_DB_PASSWORD'),
        'HOST': os.getenv('NEON_DB_HOST'),
        'PORT': os.getenv('NEON_DB_PORT'),
        'OPTIONS': {
            'sslmode': 'require',
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = 'static/'

# Directory where collectstatic copies all files for production
STATIC_ROOT = BASE_DIR / 'staticfiles'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

# WhiteNoise: compress & cache-bust static files in production
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
DATA_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB
FILE_UPLOAD_MAX_MEMORY_SIZE = 10485760  # 10MB


# ─────────────────────────────────────────────────────────────────────────────
# Add this LOGGING block to your Django settings.py
#
# Loggers used by Hero AI:
#   hero_ai.views   — all view-layer events (auth, chat_api, history, etc.)
#   hero_ai.baymax  — all Baymax AI-model events (API calls, errors, etc.)
# ─────────────────────────────────────────────────────────────────────────────

# ── Logging Setup ─────────────────────────────────────────────────────────────
# On Windows, TimedRotatingFileHandler often fails with PermissionError 
# during rotation if multiple processes (like runserver's reloader) are active.
if os.name == 'nt' and DEBUG:
    FILE_HANDLER_CLASS = "logging.FileHandler"
    FILE_HANDLER_KWARGS = {}
else:
    FILE_HANDLER_CLASS = "logging.handlers.TimedRotatingFileHandler"
    FILE_HANDLER_KWARGS = {"when": "midnight", "backupCount": 14}

# Ensure the logs directory exists to prevent deployment crashes (e.g. on Render)
LOGS_DIR = BASE_DIR / "logs"
os.makedirs(LOGS_DIR, exist_ok=True)

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,

    # ── Formatters ────────────────────────────────────────────────────────────
    "formatters": {
        "verbose": {
            "format": "[{asctime}] {levelname} {name} — {message}",
            "style":  "{",
        },
        "simple": {
            "format": "{levelname} {message}",
            "style":  "{",
        },
    },

    # ── Handlers ─────────────────────────────────────────────────────────────
    "handlers": {
        # Always print to the console (captured by gunicorn / runserver)
        "console": {
            "class":     "logging.StreamHandler",
            "formatter": "verbose",
        },
        "file": {
            "class":     FILE_HANDLER_CLASS,
            "filename":  BASE_DIR / "logs" / "hero_ai.log",
            "formatter": "verbose",
            "encoding":  "utf-8",
            **FILE_HANDLER_KWARGS,
        },
    },

    # ── Loggers ───────────────────────────────────────────────────────────────
    "loggers": {
        # Hero AI view layer
        "hero_ai.views": {
            "handlers":  ["console", "file"],
            "level":     "DEBUG",   # change to INFO in production
            "propagate": False,
        },
        # Hero AI Baymax model layer
        "hero_ai.baymax": {
            "handlers":  ["console", "file"],
            "level":     "DEBUG",
            "propagate": False,
        },
        # Catch everything else at WARNING level
        "": {
            "handlers": ["console"],
            "level":    "WARNING",
        },
    },
}