# Generated by Django 5.2.7 on 2026-07-07 04:23

import backend.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infinsight', '00001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatmessage',
            name='ai_response',
            field=backend.models.EncryptedTextField(),
        ),
        migrations.AlterField(
            model_name='chatmessage',
            name='user_message',
            field=backend.models.EncryptedTextField(),
        ),
    ]
